CREATE USER 'dms' IDENTIFIED BY '<Password>';
GRANT REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'dms' ;
GRANT ALTER, CREATE, DROP, INDEX, INSERT, UPDATE, DELETE, SELECT ON *.* TO 'dms';
GRANT ALL PRIVILEGES ON awsdms_control.* TO 'dms';
GRANT USAGE ON *.* TO 'dms' REQUIRE SSL;
